Repository CS2103JAN2018-F11-B1/main, pull requests merged in 2018-03, with the labels that each got.

#31 updates app title
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: Documentation

#30 EditCommand via alias
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: code change

#33 Feature contribution
  docs/DeveloperGuide.adoc
Labels: Documentation

#35 Update features for Woody
  docs/DeveloperGuide.adoc
Labels: Documentation

#36 Update Aboutus file
  docs/AboutUs.adoc
  docs/images/zhuleyan.png
Labels: Documentation

#28 add remark command
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Contact.java
  src/main/java/seedu/address/model/person/Lead.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/LeadContactTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: code change

#45 History Command via Alias
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: code change

#52 Exit Command via Alias
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: Documentation, code change

#51 Created tests and updated Comments
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
  src/main/java/seedu/address/logic/parser/ConvertCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Lead.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ConvertCommandTest.java
Labels: Documentation, code change

#54 describe implementation of remark command
  docs/DeveloperGuide.adoc
Labels: Documentation

#56 DocumentationChanges
  docs/DeveloperGuide.adoc
Labels: Documentation

#39 Adds color for tags
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: DO NOT MERGE

#77 Developerguide1.2v
  docs/DeveloperGuide.adoc
Labels: Documentation

#78 Userguidev1.2
  docs/UserGuide.adoc
Labels: Documentation

#104 add user stories and reprioritize them
  docs/DeveloperGuide.adoc
Labels: Documentation

#108 v1.0 to v1.2 Update: UserGuide, DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Documentation

#118 Add a sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: code change

#116 Use case for sharing to LinkedIn
  docs/DeveloperGuide.adoc
Labels: Documentation

#119 Updated MSS for duplicate detection
  docs/DeveloperGuide.adoc
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: Documentation

#120 Documentation for Duplicate Detection
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: type.epic, type.story, type.task

#124 Adds Auto-complete
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: code change, enhancement

#125 Add annotation
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
Labels: Documentation

#123 Adding Docs to previous weeks
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ConvertSequenceDiagram1.png
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
  src/main/java/seedu/address/logic/parser/ConvertCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Contact.java
  src/main/java/seedu/address/model/person/Lead.java
  src/main/java/seedu/address/model/person/Type.java
  src/test/java/seedu/address/logic/commands/ConvertCommandTest.java
Labels: Documentation

#126 Documentation1.3
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/ui/PersonCard.java
Labels: Documentation

#122 Userguide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/RemarkCommandDiagram.png
Labels: Documentation

#127 Add one line to import image correctly
  docs/DeveloperGuide.adoc
Labels: Documentation

#129 Adding editdetails to User Guide
  docs/UserGuide.adoc
Labels: Documentation

#121 Duplicate detection
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/LinkedInLoginCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: type.epic, type.story, type.task

#132 Code credit
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/Oauth2Client.java
  src/main/java/seedu/address/commons/events/ui/ShowBrowserRequestEvent.java
  src/main/java/seedu/address/logic/commands/LinkedInLoginCommand.java
  src/main/java/seedu/address/logic/commands/ShareToLinkedInCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ShareToLinkedInCommandParser.java
  src/main/java/seedu/address/ui/BrowserWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: Documentation

#133 DocChange
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentCommandClassDiagram.pptx
  docs/images/LinkedInLoginSequenceDiagram.png
  docs/images/LogicCommandClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: Documentation
