Repository CS2103JAN2018-F11-B1/main, pull requests merged in 2018-04, with the labels that each got.

#139 update UserGuide for import command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Documentation

#140 Add an ImportCommand
  build.gradle
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Labels: code change

#136 Author Annotation and Updated MSS
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: Documentation

#137 Adds Change theme command
  src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ChangeThemeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Exception/InputThemeEqualsCurrentThemeException.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Theme.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ExtensionsLight.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindowLight.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: code change, enhancement

#141 Display list of Leads and Contacts
  src/main/java/seedu/address/logic/commands/DisplayCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DisplayCommandParser.java
  src/main/java/seedu/address/model/person/TypeMatchesKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/DisplayCommandTest.java
Labels: enhancement, priority.high

#143 v1.4 Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/LogicComponentCommandClassDiagram.pptx
  docs/images/DisplayListOfACertainTypeActionDiagram.png
Labels: Documentation

#144 Documentation1.4
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: Documentation

#145 updates Changetheme command
  src/main/resources/view/LightTheme.css
Labels: code change

#146 Updated my responsibilities
  docs/AboutUs.adoc
Labels: Documentation

#152 Code annotation
  src/test/java/seedu/address/logic/commands/LinkedInLoginCommandTest.java
Labels: Documentation

#150 Login and share defense
  src/main/java/seedu/address/commons/core/Oauth2Client.java
  src/main/java/seedu/address/logic/commands/ShareToLinkedInCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: code change, enhancement

#149 Adding Accounts to Contacts
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
  src/main/java/seedu/address/logic/commands/EditDetailsCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/account/Account.java
  src/main/java/seedu/address/model/account/UniqueAccountList.java
  src/main/java/seedu/address/model/person/Contact.java
  src/main/java/seedu/address/storage/XmlAdaptedAccount.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: code change, enhancement

#157 Documentation1.4
  collated/functional/Liu.md
  collated/test/Liu.md
  collated/unused/Liu.md
Labels: Documentation

#158 updates ui to include a welcome page
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/default.html
  src/main/resources/view/welcome.png
Labels: code change

#162 v1.4 Update UI
  docs/images/Ui.png
Labels: Documentation

#177 Add acknowledgement in readme.adoc
  README.adoc
Labels: Documentation

#199 Adds ChangeThemeCommandTest and ChangeThemePaserTest
  src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
  src/test/java/seedu/address/logic/parser/ChangeThemeCommandParserTest.java
Labels: code change

#198 Clear command system test
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: code change

#202 Resolve the remark issue
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
Labels: code change

#200 As a salesperson, I can find a lead or contact by phone number and email address
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.medium, type.story

#204 Display error message when importing wrong format data in csv file
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Labels: code change

#205 Specify the import command
  docs/UserGuide.adoc
Labels: Documentation

#210 Improves change theme command
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/events/ui/ChangeThemeRequestEvent.java
  src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
  src/main/java/seedu/address/model/Exception/InputThemeEqualsCurrentThemeException.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Theme.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/ExtensionsLight.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MainWindowLight.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
Labels: code change, enhancement

#211 Fix editdetails
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditDetailsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditDetailsCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/account/Account.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: code change

#214 Improve dev guide & Add reused annotation
  docs/DeveloperGuide.adoc
  docs/images/ImportCommandSequenceDiagram.png
  docs/images/RemarkCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
Labels: Documentation

#212 Author annotation of team members for collation
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: code change

#217 Enables it to tell users the index of person in csv file who has wrong format
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Labels: code change

#197 Personal Portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Sheikh-Umar.adoc
Labels: Documentation

#218 Fix save config bug
  src/main/java/seedu/address/commons/core/Oauth2Client.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: code change

#222 Edited DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: Documentation

#223 Personal Portfolio updates
  docs/AboutUs.adoc
  docs/images/Ui.png
  docs/team/Sheikh-Umar.adoc
Labels: Documentation

#213 Portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ConvertSequenceDiagram2.png
  docs/team/WoodyLau.adoc
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
Labels: Documentation

#225 Add Account command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AccountCommand.java
  src/main/java/seedu/address/logic/commands/EditDetailsCommand.java
  src/main/java/seedu/address/logic/parser/AccountCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: enhancement

#228 Personal portfolio
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/DavidTen.adoc
  docs/team/WoodyLau.adoc
Labels: Documentation

#230 Updates autocomplete for v1.5rc
  src/main/java/seedu/address/commons/core/Messages.java
Labels: code change

#231 annotate change theme command tests
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
  src/test/java/seedu/address/logic/parser/ChangeThemeCommandParserTest.java
Labels: Documentation

#229 Documentation1.5rc
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/liuyiming.adoc
Labels: Documentation

#235 Change annotation
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
Labels: Documentation

#237 removes whitespace for portfolio
  docs/team/liuyiming.adoc
Labels: Documentation

#238 Code Collation
  collated/functional/zhuleyan-reused.md
  collated/functional/zhuleyan.md
  collated/test/zhuleyan-reused.md
  collated/test/zhuleyan.md
Labels: Collation

#241 Personal Portfolio
  docs/AboutUs.adoc
  docs/team/Sheikh-Umar.adoc
Labels: Documentation

#243 Fix portfolio links
  docs/UserGuide.adoc
  docs/team/WoodyLau.adoc
Labels: Documentation

#244 Fix Title not going through Converts
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
Labels: code change

#246 Portfolio
  docs/team/zhuleyan.adoc
Labels: Documentation

#245 Updates the change theme command in DG
  docs/DeveloperGuide.adoc
  docs/images/ChangeThemeHighLevelSequenceDiagrams.png
  docs/images/ChangeThemeLogicComponentSequenceDiagram.png
  docs/team/liuyiming.adoc
Labels: Documentation

#248 documentation changes
  docs/team/liuyiming.adoc
  src/main/java/seedu/address/model/Exception/InputThemeEqualsCurrentThemeException.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/resources/view/ExtensionsLight.css
  src/main/resources/view/MainWindowLight.fxml
Labels: Documentation

#251 Add Parent Company Tag feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddParentCompanyTag.png
Labels: Documentation

#253 Add testing
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: code change

#254 Documentation updates
  README.adoc
  docs/DeveloperGuide.adoc
  docs/images/AddParentCompanyTag.png
  docs/images/AddParentCompanyTagActivityDiagram.png
  docs/images/DetectDuplicateActivityDiagram.png
  docs/images/DisplayListOfACertainTypeActivityDiagram.png
  docs/team/Sheikh-Umar.adoc
Labels: Documentation

#258 Add Manual testing and modify import command
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/exceptions/WrongFileFormatException.java
Labels: Documentation, code change

#255 Documentation updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Sheikh-Umar.adoc
Labels: Documentation

#256 Added Manual testing instructions
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
Labels: Documentation

#257 Fix the deleting of fields from editdetails
  src/main/java/seedu/address/ui/PersonCard.java
Labels: code change

#262 adds GuiThemeSettingTest
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/ui/GuiThemeSettingTest.java
Labels: code change

#263 adds testing instruction for change theme
  docs/DeveloperGuide.adoc
Labels: Documentation

#261 David Code quality part 2
  docs/DeveloperGuide.adoc
  docs/diagrams/LinkedInShareSequenceDiagram.pptx
  docs/diagrams/LoadGoogleMapsSequenceDiagram.pptx
  docs/diagrams/SaveGoogleLocationSequenceDiagram.pptx
  docs/images/LinkedInShareSequenceDiagram.png
  docs/images/LoadGoogleMapsSequenceDiagram.png
  docs/images/SaveGoogleLocationSequenceDiagram.png
  docs/team/DavidTen.adoc
  src/main/java/seedu/address/commons/core/Oauth2Client.java
  src/main/java/seedu/address/logic/commands/GoogleSetLocationCommand.java
  src/main/java/seedu/address/logic/commands/ShareToLinkedInCommand.java
  src/main/java/seedu/address/logic/parser/GoogleSetLocationCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/parser/GoogleSetLocationCommandParserTest.java
Labels: Documentation, code change

#266 Better error message
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/GoogleSetLocationCommand.java
  src/main/java/seedu/address/ui/BrowserWindow.java
Labels: Documentation, code change

#267 Code Collation
  collated/functional/A0155428B.md
  collated/functional/WoodyLau.md
  collated/functional/davidten.md
  collated/functional/zhuleyan.md
  collated/test/A0155428B.md
  collated/test/WoodyLau.md
  collated/test/davidten.md
  collated/test/zhuleyan.md
  collated/unused/A0155428B.md
Labels: Collation
